
		align	4
		label	L823_len__hla_ word
		dd	0fh
		dd	0fh
		label	L823_str__hla_ byte
		db	"Surface Area = "
		db	0


		align	4
		label	L837_len__hla_ word
		dd	02dh
		dd	02dh
		label	L837_str__hla_ byte
		db	"Lemme calculate the surface area of a sphere!"
		db	0

		db	0
		db	0

		align	4
		label	L855_len__hla_ word
		dd	09h
		dd	09h
		label	L855_str__hla_ byte
		db	"Gimme r: "
		db	0

		db	0
		db	0
