
		align	4
		label	L839_len__hla_ word
		dd	09h
		dd	09h
		label	L839_str__hla_ byte
		db	"Gimme X: "
		db	0

		db	0
		db	0

		align	4
		label	L861_len__hla_ word
		dd	09h
		dd	09h
		label	L861_str__hla_ byte
		db	"Gimme Y: "
		db	0

		db	0
		db	0

		align	4
		label	L883_len__hla_ word
		dd	09h
		dd	09h
		label	L883_str__hla_ byte
		db	"Gimme z: "
		db	0

		db	0
		db	0

		align	4
		label	L905_len__hla_ word
		dd	013h
		dd	013h
		label	L905_str__hla_ byte
		db	"After sorting, X = "
		db	0


		align	4
		label	L919_len__hla_ word
		dd	06h
		dd	06h
		label	L919_str__hla_ byte
		db	", Y = "
		db	0

		db	0

		align	4
		label	L933_len__hla_ word
		dd	06h
		dd	06h
		label	L933_str__hla_ byte
		db	", Z = "
		db	0

		db	0
