
		align	4
		label	L842_len__hla_ word
		dd	05h
		dd	05h
		label	L842_str__hla_ byte
		db	"EBX: "
		db	0

		db	0
		db	0

		align	4
		label	L871_len__hla_ word
		dd	020h
		dd	020h
		label	L871_str__hla_ byte
		db	"Please enter a string to process"
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L889_len__hla_ word
		dd	026h
		dd	026h
		label	L889_str__hla_ byte
		db	"----> here is the string you entered: "
		db	0

		db	0

		align	4
		label	L903_len__hla_ word
		dd	07h
		dd	07h
		label	L903_str__hla_ byte
		db	"result="
		db	0

