
		align	4
		label	L822_len__hla_ word
		dd	018h
		dd	018h
		label	L822_str__hla_ byte
		db	"Provide a first number: "
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L844_len__hla_ word
		dd	01ah
		dd	01ah
		label	L844_str__hla_ byte
		db	"Provide an second number: "
		db	0

		db	0

		align	4
		label	L871_len__hla_ word
		dd	01h
		dd	01h
		label	L871_str__hla_ byte
		db	"_"
		db	0

		db	0
		db	0
