
		align	4
		label	L825_len__hla_ word
		dd	017h
		dd	017h
		label	L825_str__hla_ byte
		db	"Feed me(2 hex digits): "
		db	0


		align	4
		label	L863_len__hla_ word
		dd	012h
		dd	012h
		label	L863_str__hla_ byte
		db	"First class ticket"
		db	0

		db	0

		align	4
		label	L882_len__hla_ word
		dd	0eh
		dd	0eh
		label	L882_str__hla_ byte
		db	"Economy ticket"
		db	0

		db	0

		align	4
		label	L901_len__hla_ word
		dd	07h
		dd	07h
		label	L901_str__hla_ byte
		db	"No bags"
		db	0


		align	4
		label	L926_len__hla_ word
		dd	06h
		dd	06h
		label	L926_str__hla_ byte
		db	" bags "
		db	0

		db	0

		align	4
		label	L945_len__hla_ word
		dd	07h
		dd	07h
		label	L945_str__hla_ byte
		db	"No meal"
		db	0


		align	4
		label	L964_len__hla_ word
		dd	0eh
		dd	0eh
		label	L964_str__hla_ byte
		db	"Meal purchased"
		db	0

		db	0

		align	4
		label	L988_len__hla_ word
		dd	0bh
		dd	0bh
		label	L988_str__hla_ byte
		db	"miles flown"
		db	0


		align	4
		label	L1006_len__hla_ word
		dd	0fh
		dd	0fh
		label	L1006_str__hla_ byte
		db	"Total Fees = $ "
		db	0


		align	4
		label	L1027_len__hla_ word
		dd	01bh
		dd	01bh
		label	L1027_str__hla_ byte
		db	"Miles flown cannot be zero!"
		db	0

