
		align	4
		label	L836_len__hla_ word
		dd	012h
		dd	012h
		label	L836_str__hla_ byte
		db	" is in the middle!"
		db	0

		db	0

		align	4
		label	L854_len__hla_ word
		dd	0bh
		dd	0bh
		label	L854_str__hla_ byte
		db	"Feed Me X: "
		db	0


		align	4
		label	L876_len__hla_ word
		dd	0bh
		dd	0bh
		label	L876_str__hla_ byte
		db	"Feed Me Y: "
		db	0


		align	4
		label	L898_len__hla_ word
		dd	0bh
		dd	0bh
		label	L898_str__hla_ byte
		db	"Feed Me Z: "
		db	0


		align	4
		label	L921_len__hla_ word
		dd	06h
		dd	06h
		label	L921_str__hla_ byte
		db	"AL = 0"
		db	0

		db	0

		align	4
		label	L936_len__hla_ word
		dd	01ch
		dd	01ch
		label	L936_str__hla_ byte
		db	"X and Y and Z are all equal!"
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L954_len__hla_ word
		dd	06h
		dd	06h
		label	L954_str__hla_ byte
		db	"AL = 1"
		db	0

		db	0
